name: Tests

on: workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        pip install flake8 pytest pytest-cov 
        pip install opendp==0.8.0 
        pip install opendp_logger==0.3.0
    - name: Run flake8
      run: flake8 .
    - name: Run pytest and generate test coverage report in html
      run: | 
        pytest -v --cov-report html:cov_html --cov=server
        cp cov_html/* .
    - name: Push report files to dedicated repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_REPORT }}
      with:
        source-directory: ./
        destination-github-username: 'lamd91'
        destination-repository-name: 'test-coverage-report'
        target-branch: main
        target-directory: html/
        
